<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
    <UserSecretsId>28225755-a527-413a-95b9-58f440ed9ebb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="8.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="8.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.6" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\OneTheater.Common.Application\OneTheater.Common.Application.csproj" />
    <ProjectReference Include="..\..\Common\OneTheater.Common.Infrastructure\OneTheater.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Common\OneTheater.Common.Presentation\OneTheater.Common.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\Users\OneTheater.Modules.Users.Infrastructure\OneTheater.Modules.Users.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Shows\OneTheater.Modules.Shows.Infrastructure\OneTheater.Modules.Shows.Infrastructure.csproj" />
  </ItemGroup>

</Project>

