//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OneTheater.Modules.Users.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Create_UserEmail : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "email",
                schema: "users",
                table: "users",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "first_name",
                schema: "users",
                table: "users",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "last_name",
                schema: "users",
                table: "users",
                type: "text",
                nullable: false,
                defaultValue: "");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "email",
                schema: "users",
                table: "users");

            migrationBuilder.DropColumn(
                name: "first_name",
                schema: "users",
                table: "users");

            migrationBuilder.DropColumn(
                name: "last_name",
                schema: "users",
                table: "users");
        }
    }
}
