//<autogenerated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OneTheater.Modules.Shows.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Create_Show : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "movies",
                schema: "shows",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_movies", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "shows",
                schema: "shows",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    movie_id = table.Column<Guid>(type: "uuid", nullable: false),
                    show_time = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    screen_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_shows", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "theaters",
                schema: "shows",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_theaters", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "screens",
                schema: "shows",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "text", nullable: false),
                    theater_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_screens", x => x.id);
                    table.ForeignKey(
                        name: "fk_screens_theaters_theater_id",
                        column: x => x.theater_id,
                        principalSchema: "shows",
                        principalTable: "theaters",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "seats",
                schema: "shows",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    screen_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_seats", x => x.id);
                    table.ForeignKey(
                        name: "fk_seats_screens_screen_id",
                        column: x => x.screen_id,
                        principalSchema: "shows",
                        principalTable: "screens",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "seats_inventories",
                schema: "shows",
                columns: table => new
                {
                    show_id = table.Column<Guid>(type: "uuid", nullable: false),
                    screen_id = table.Column<Guid>(type: "uuid", nullable: false),
                    seat_id = table.Column<Guid>(type: "uuid", nullable: false),
                    seat_number = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    status = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_seats_inventories", x => new { x.screen_id, x.seat_id, x.show_id });
                    table.ForeignKey(
                        name: "fk_seats_inventories_screens_screen_id",
                        column: x => x.screen_id,
                        principalSchema: "shows",
                        principalTable: "screens",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_seats_inventories_shows_show_id",
                        column: x => x.show_id,
                        principalSchema: "shows",
                        principalTable: "shows",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_screens_theater_id",
                schema: "shows",
                table: "screens",
                column: "theater_id");

            migrationBuilder.CreateIndex(
                name: "ix_seats_screen_id",
                schema: "shows",
                table: "seats",
                column: "screen_id");

            migrationBuilder.CreateIndex(
                name: "ix_seats_inventories_show_id",
                schema: "shows",
                table: "seats_inventories",
                column: "show_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "movies",
                schema: "shows");

            migrationBuilder.DropTable(
                name: "seats",
                schema: "shows");

            migrationBuilder.DropTable(
                name: "seats_inventories",
                schema: "shows");

            migrationBuilder.DropTable(
                name: "screens",
                schema: "shows");

            migrationBuilder.DropTable(
                name: "shows",
                schema: "shows");

            migrationBuilder.DropTable(
                name: "theaters",
                schema: "shows");
        }
    }
}
