// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneTheater.Modules.Shows.Infrastructure.Database;

#nullable disable

namespace OneTheater.Modules.Shows.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ShowsDbContext))]
    [Migration("20240805162658_Add_Outbox")]
    partial class Add_Outbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shows")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneTheater.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "shows");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", "shows");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_movies");

                    b.ToTable("movies", "shows");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.Screens.Screen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("uuid")
                        .HasColumnName("theater_id");

                    b.HasKey("Id")
                        .HasName("pk_screens");

                    b.HasIndex("TheaterId")
                        .HasDatabaseName("ix_screens_theater_id");

                    b.ToTable("screens", "shows");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("name");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid")
                        .HasColumnName("screen_id");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("ScreenId")
                        .HasDatabaseName("ix_seats_screen_id");

                    b.ToTable("seats", "shows");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.SeatsInventories.SeatsInventory", b =>
                {
                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid")
                        .HasColumnName("show_id");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid")
                        .HasColumnName("screen_id");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("seat_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("ShowId", "SeatId")
                        .HasName("pk_seats_inventories");

                    b.HasIndex("ScreenId")
                        .HasDatabaseName("ix_seats_inventories_screen_id");

                    b.ToTable("seats_inventories", "shows");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.Shows.Show", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid")
                        .HasColumnName("screen_id");

                    b.Property<DateTimeOffset>("ShowTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("show_time");

                    b.HasKey("Id")
                        .HasName("pk_shows");

                    b.ToTable("shows", "shows");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.Theaters.Theater", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_theaters");

                    b.ToTable("theaters", "shows");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.Screens.Screen", b =>
                {
                    b.HasOne("OneTheater.Modules.Shows.Domain.Theaters.Theater", "Theater")
                        .WithMany()
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screens_theaters_theater_id");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.Seats.Seat", b =>
                {
                    b.HasOne("OneTheater.Modules.Shows.Domain.Screens.Screen", "Screen")
                        .WithMany("Seats")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seats_screens_screen_id");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.SeatsInventories.SeatsInventory", b =>
                {
                    b.HasOne("OneTheater.Modules.Shows.Domain.Screens.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seats_inventories_screens_screen_id");

                    b.HasOne("OneTheater.Modules.Shows.Domain.Shows.Show", "Show")
                        .WithMany("SeatsInventories")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seats_inventories_shows_show_id");

                    b.Navigation("Screen");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.Screens.Screen", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("OneTheater.Modules.Shows.Domain.Shows.Show", b =>
                {
                    b.Navigation("SeatsInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
